#!/bin/bash

sudo cp kodi /usr/local/bin
sudo chmod 755 /usr/local/bin/kodi

sudo cp kodi.desktop /usr/share/applications/kodi.desktop
sudo chmod 755 /usr/share/applications/kodi.desktop

sudo cp tv.kodi.Kodi.png /usr/share/images/kodi.png
