#!/bin/bash

docker run -it --rm --name kodi --net=host --privileged -v /dev:/dev --env="DISPLAY" --env="USER" -v /etc/timezone:/etc/timezone:ro -v $HOME:$HOME -v /media:/media -v /etc/passwd:/etc/passwd:ro -v /etc/group:/etc/group:ro -v /etc/shadow:/etc/shadow:ro -v /run/user/$uid:/run/user/$uid jpmsb/kodi:18.7
